Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
  config.vm.box = "debian/buster64"
  server.vm.hostname = "server"
  server.vm.network "public_network"
  server.vm.provision "file", source: "index.html", destination: "index.html"
  server.vm.provision "shell", inline: "mv index.html /var/www/html/index.html"
  server.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y apache2
  SHELL
  end
end

